### ISSUE TITLE
Instruction in the README Don't Work!

### ISSUE THREAD

**Issue by ghaffarian** [ghaffarian/progviz#1]
The **"Getting Started"** instruction in the README file are both incomplete and invalid!

I did `npm install` and then `npm run start` and this is what I get:

![screenshot from 2017-10-01 14-37-57](https://user-images.githubusercontent.com/3057336/31054024-631aac44-a6b6-11e7-8c71-cf4cbe9450ec.png)

Please fix this as soon as possible so I can see the latest interface you have developed.

Then I will update the README myself, with appropriate instructions.

**Comment by aliizadi** [comment]
There were two bugs:
1- Sources of w3.css and material icons haven't been added but now I pushed them and they are available in style folder so the app style works now!
2- Due to one bug in dagre-d3 you should change some file contents in node_modules that I added its instruction to README.md.
I opened an issue for this bug in dagred3 repo (https://github.com/cpettitt/dagre-d3/issues/285)
but it wasn't fixed
Because of this you have to change some files content after installing dependencies by npm install

**Comment by ghaffarian** [comment]
Thanks.
Yes this fixed the problem.
I further improved the instructions in the README.
